### ISSUE TITLE
Frequency is still off by 10hz

### ISSUE THREAD

**Issue by dbloemhard** [vodka-bears/LiteVTX#1]
Hi this is Tokyo_Dom from RCGroups forums... As mentioned on there, i found that the frequency is still off by about 10hz (set to 5705, the peak was from 5683 to 5705 so the median would be 5694...)

I have another question/issue that i will raise in a separate thread
![231395](https://user-images.githubusercontent.com/39540755/97129372-162a7280-1782-11eb-9297-d4ee3e98d2ce.jpg)
![231396](https://user-images.githubusercontent.com/39540755/97129377-1aef2680-1782-11eb-8767-80c6acfd0653.jpg)

**Comment by vodka-bears** [comment]
Hi. Thanks for pointing me out. I replied to you at RCGroups. I'll buy a rotg this (I hope) week and fix that soon.

**Comment by vodka-bears** [comment]
So I made some measurements and found out that both median and mean offset were -6.5 MHz. So I'll simply make +7 MHz to every frequency in the list and hope for the best.

**Comment by dbloemhard** [comment]
Great! I'm sure that will be fine. I cannot actually see the top of the
peak (well maybe i could - just need to take it further away) but that
sounds about right.

I thought about trying to modify it myself but i couldnt work out how the
arrays in freq.h corresponded to actual vtx frequencies.

Instead I made some more improvements to the OSD; I added a menu option for
the RSSI warning level so that it can be configured via the OSD. I flew it
around my apartment though and the RSSI didnt drop all that much... will
have to see on an outdoors flight. But now i would like to add another
option for the crosshairs position - it was a bit high for the canopy i was
using (and i might like the option to turn it off), as well as an option to
hide all OSD details (except warnings) via a channel assignment

**Comment by vodka-bears** [comment]
These values are described at page 7 of this document. https://datasheetspdf.com/pdf-file/791496/RichWave/RTC6705/1. I used a python script to generate arrays definition.

**Comment by dbloemhard** [comment]
Thanks! I look forward to trying it - unfortunately i wont get a chance until next week.
I hear from a friend that his latest Lite FC V2 doesnt have the frequency shift issue - or not as much as previous revisions. I wonder if they fixed the oscillator, or its a new VTX firmware.
If it turns out the oscillator shift is random, it might be good to pass in a variable to let you adjust the shift via silverware (easier to flash than soldering on the C2D and C2CK wires)
