### ISSUE TITLE
Enhancement request - turn the vtx LED off when 200mw is selected

### ISSUE THREAD

**Issue by dbloemhard** [vodka-bears/LiteVTX#2]
This is mainly a personal request, i would like to implement it myself however i do not have a compile environment for C51 - Keil has the size limit on the evaluation version.

I'd like to disable all LEDs if possible, so i made LEDs switchable via a channel (broken in the Betafpv source - check out my RGB implementation btw!), however the board LED, and the VTX LED cannot be disabled currently. I thought maybe if i set the VTX channel to 200mw (not supported on this VTX), then perhaps that could be a signal for the VTX to disable the LED?

That still leaves the board LED, but i can desolder that. Your VTX code gives that LED a much more important feature though so i'd like to keep that if possible

**Comment by vodka-bears** [comment]
Hi. Keil C51 evaluation version has limit of 16k، efm8bb2 has flash size 16k. This project doesn't even make 2k. If a binary for efm8bb2 doesn't fit into Keil free limit it won't fit into the flash.

To disable vtx led with "200 mW" option add somewhere a disable led flag, copy lines 29-34 of Interrupts.c, paste after line 34. In a copied segment compare UART_Buffer[2] to 5 not 7. Also remove the unnecessary checks for channel range and current channel. Set a disable led flag according to the payload, UART_Buffer[4]. I don't remember which value indicates which power so refer to osd.c of Silverware. Also remember that the vtx led is in open drain mode so LED = 0 is ON and 1 is OFF. Good luck sneaking.

If you want to store this setting permanently check read_chan_from_mem and write_chan_to_mem in main.c.

**Comment by dbloemhard** [comment]
Oh great! I thought i saw 2kb limit, which is tiny...
I will download it and have a go. Now that i have the BB2 programmer, this board has become a little more fun again :)

**Comment by vodka-bears** [comment]
Oh no I was wrong. It's 2k of "object code" whatever that means. However the thing fits into Keil free limit as well as a much larger osd code. I neither paid a cent to Keil nor pirated it and succeeded to build both.

**Comment by dbloemhard** [comment]
Indeed i was confused by that bit. Anyway i have now built the code, i will try flashing it as-is before trying out the code changes you so generously spelt out for me :) 
However a binary comparison of my built hex file is slightly different to yours
![image](https://user-images.githubusercontent.com/39540755/97187889-40158080-17e6-11eb-92a7-4579a1ae227d.png)
Was i supposed to change any of the project settings? I basically just opened the project confirmed the target was the EFM8BB2etc and then pressed build

**Comment by dbloemhard** [comment]
Never mind it seems to work fine when flashed. Now to implement that change

**Comment by vodka-bears** [comment]
Maybe a different Keil version. Maybe there's some change I made after publishing the hex lol. Anyway there will be changes soon after I receive a ROTG01 Pro I ordered from BG Russian warehouse today. Also I want to organize my repos differently so it's already outdated.

**Comment by dbloemhard** [comment]
Ok no problems. So lucky to have a local BG warehouse... I have to wait minimum 2 weeks sometimes a month or more.

Anyway the changes you suggested work fine, i wont do the pull request or anything since its more likely to confuse others. Now to build and flash the OSD! I wanted to add RSSI on the screen, in terms of PPS from the bayang receiver, quite useful info (moreso than seeing 'BAYANG' on the screen thats for sure!)

**Comment by dbloemhard** [comment]
```
Build started: Project: LiteOSD
Build target 'LiteOSD'
assembling SILABS_STARTUP.A51...
compiling main.c...
compiling InitDevice.c...
compiling Interrupts.c...
compiling show.c...
linking...
BL51 BANKED LINKER/LOCATER V6.22.2.0 - SN: Eval Version
COPYRIGHT ARM Germany GmbH 1987 - 2017
".\Objects\SILABS_STARTUP.obj",
".\Objects\main.obj",
".\Objects\InitDevice.obj",
".\Objects\Interrupts.obj",
".\Objects\show.obj" 
TO ".\Objects\LiteOSD" 
PRINT(".\Listings\LiteOSD.m51") RAMSIZE(256) 
******************************************************************************
* RESTRICTED VERSION WITH 0800H BYTE CODE SIZE LIMIT; USED: 30B0H BYTE (608%) *
******************************************************************************
Program Size: data=9.0 xdata=130 code=12723
LINK/LOCATE RUN COMPLETE.  0 WARNING(S),  0 ERROR(S)
*** FATAL ERROR L250: CODE SIZE LIMIT IN RESTRICTED VERSION EXCEEDED
    MODULE:  C:\KEIL_V5\C51\LIB\C51C.LIB (-----)
    LIMIT:   0800H BYTES
Target not created.
Build Time Elapsed:  00:00:02
```
Ooft that sucks

**Comment by vodka-bears** [comment]
I somehow managed to overcome this. I installed Simplicity Studio, did some tambourine dancing and at some stage it began to work.

**Comment by dbloemhard** [comment]
Just found a post by a Japanese user who said something similar. Actually he just imported the keil project into SS and then it compiled without problems I'm downloading it now, will check tomorrow

**Comment by vodka-bears** [comment]
I build with Keil, it somehow forgot about its own limitations after I did something with SS.

**Comment by dbloemhard** [comment]
So, the first time you build a project in Simplicity Studio (using the Keil toolchain for compilation), it warns you about the Keil evaluation license, AND offers you a link to get a single user license from Keil. When you go to that page you will get a license code emailed to you, which you can put into the dialog of Silicon Studio to enable compilation from there. However compiling from Keil will still not work.

You need to apply that license to Keil as well - start Keil uVision as Administrator (right click, execute as administrator), then go to File, License Management, and paste in the code that was emailed to you. Make sure you go to Project, Clean Targets before rebuilding your project in Keil and it should just work.

**Comment by dbloemhard** [comment]
In the past few months i have installed:
Arduino IDE
Android Studio
Keil uVision
VS Code
STM Studio/STMCubeMX/STMCubeProgrammer
Python
Simplicity Studio

Would be lovely if i could just consolidate this into one IDE (I think thats possible with VS Code, but havent looked into it)

Not to mention all of the quad configuration tools like BLHeli Suite, configurator, Jesc configurator, emu flight configurator, betaflight configurator, OpenTX companion, St-Link utility, DFu utilities, and the list goes on

**Comment by dbloemhard** [comment]
![image](https://user-images.githubusercontent.com/39540755/97260104-9d014d00-185f-11eb-94f5-cf408cfcd23a.png)
What do you think about that ;)
Added the rssi symbol (actually two characters)
Modified silverware to send packets per second, instead of protocol
display the packets per second and that symbol where it displayed the protocol before

I'll update the Lite Silverware repository on my fork since i have done a bunch of changes on my side; if its any interest to you i will fork your OSD and i can create a pull request (or you can just add the changes)

**Comment by vodka-bears** [comment]
Wow cool. Is it a reliable substitute for RSSI? Does it exceed 100 in close range?

**Comment by dbloemhard** [comment]
I did not see it go over 100. It is packets per second / 2 which is clamped to 255 in the code, but for some reason it never goes above 100. It is the same value that is sent back in Bayang telemetry (however this is not very useful because when that number starts to drop to dangerous levels, you typically already lost telemetry connection). Only thing is that this only updates once per second,,, so its not as dynamic as regular RSSI display

I have previously also modified silverware to get the RSSI from SBUS channel 16 (Frsky receivers), so it can be made to work with an external receiver too.

I will make some small changes i think - to make this backwards compatible with the Lite FC firmware that doesnt send RSSI data - currently using osd_data[5] that was sending the rx_switch value, but then it might still be useful to see the protocol when RSSI is zero (i.e. not bound)

**Comment by vodka-bears** [comment]
Please make a pull request to both osd and silverware. I'll check and merge after I receive my rotg and tune the vtx.
